name: Have built-in roles and permissions changed?

on:
  workflow_dispatch: {}
  schedule:
    - cron: "00 01 * * *"   # Every day at 1:00 AM UTC

permissions:
  contents: write
  id-token: write

jobs:
  have_builtin_roles_and_permissions_changed:
    runs-on: ubuntu-latest
    steps:
    - name: Az Login
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302   # v2.2.0
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - name: Get ARM access token
      id: get-arm-token
      run: echo "token=$(az account get-access-token --resource=https://management.azure.com --query accessToken -o tsv)" >> $GITHUB_OUTPUT

    - name: Get MS Graph access token
      id: get-graph-token
      run: echo "token=$(az account get-access-token --resource=https://graph.microsoft.com --query accessToken -o tsv)" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037   # v4.2.2

    - name: Run AzRoleWatcher
      uses: ./.github/actions/pull-for-changes
      env:
        ARM_ACCESS_TOKEN: ${{ steps.get-arm-token.outputs.token }}
        MSGRAPH_ACCESS_TOKEN: ${{ steps.get-graph-token.outputs.token }}
      with:
        user_email: 'AzRoleWatcher-robot@gmail.com'
        user_name: 'AzRoleWatcher-robot'
