name: Have built-in roles and permissions changed?
on:
  workflow_dispatch:
  schedule:
    - cron: "00 01 * * *"

jobs:
  have_builtin_roles_and_permissions_changed:
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      SP_CREDENTIALS_ENTRA: ${{ secrets.SP_CREDENTIALS_ENTRA }}
    steps:
    - name: Checkout
      uses: emiliensocchi/actions@checkout
    - name: Run AzRoleWatcher
      uses: ./.github/actions/pull-for-changes
      with:
        user_email: 'emilien.socchi@gmail.com'
        user_name: 'emiliensocchi'
